IndexError: string index out of range
If there is a tag `,` at the end of the line or the beginning of the line in the list
The program will stop
This is due to line [161](https://github.com/codingo/Interlace/edit/master/Interlace/lib/core/input.py#L161) and [187](https://github.com/codingo/Interlace/edit/master/Interlace/lib/core/input.py#L187)
Because this line [187](https://github.com/codingo/Interlace/edit/master/Interlace/lib/core/input.py#L187) checks for some characters in the string
The chain will be empty due to split [161](https://github.com/codingo/Interlace/edit/master/Interlace/lib/core/input.py#L161)
This causes the script to stop with the error `IndexError: string index out of range`